# Qdrant configuration for Symbi-OSINT vector database
service:
  http_port: 6333
  grpc_port: 6334
  enable_cors: true

storage:
  # Storage backend configuration
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  temp_path: /qdrant/temp
  
  # Performance settings
  max_segment_size_kb: 20000
  wal_capacity_mb: 32
  wal_segments_ahead: 0
  
  # Vector index settings
  hnsw_config:
    m: 16
    ef_construct: 200
    full_scan_threshold: 10000
    max_indexing_threads: 0
    
  # Optimization settings
  optimizers_config:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size_kb: 20000
    memmap_threshold_kb: 200000
    indexing_threshold_kb: 20000
    flush_interval_sec: 5
    max_optimization_threads: 1

# Cluster configuration (disabled for single-node)
cluster:
  enabled: false

# API configuration  
api:
  enable_cors: true
  max_request_size_mb: 32
  max_workers: 0

# Telemetry
telemetry:
  disabled: false

# Log level
log_level: INFO